[pytest]

# Always add these command line flags (e.g., -s to print to console, -v for verbose)
# Note: This tells Pytest: "If the test passes, delete the videos to save hard drive space. If the test fails, lock the doors and save everything."
addopts = -s -v --tracing=retain-on-failure --screenshot=only-on-failure --video=retain-on-failure --alluredir=allure-results

# Register our custom markers so Pytest stops throwing warnings
markers =
    ui: mark a test as a UI test
    api: mark a test as a backend API test
    e2e: mark a test as a full end-to-end flow
pythonpath = .

